force-app/main/default/objects/Item__c/fields/All_Copies__c.field-meta.xml
<CustomField>
    <fullName>All_Copies__c</fullName>
    <defaultValue>1</defaultValue>
    <label>All Copies</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <label>Surname</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Rent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Returning_Date__c.field-meta.xml
<CustomField>
    <fullName>Returning_Date__c</fullName>
    <description>Date when an item should be returned to the library.</description>
    <label>Returning Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>reserved</fullName>
                <default>true</default>
                <label>reserved</label>
            </value>
            <value>
                <fullName>borrowed</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/RentalStatusSchedulerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class RentalStatusSchedulerTest {

    @testSetup
    static void setupTestData() {
        Item__c book = new Item__c(Name = 'Book 1', All_Copies__c = 10, RecordTypeId = RecordTypesUtility.getRecordTypeId(Item__c.SobjectType, 'Book'));
        insert book;
        Person__c person = new Person__c(Name__c = 'Test', Surname__c = 'Test', RecordTypeId = RecordTypesUtility.getRecordTypeId(Person__c.SobjectType, 'Client'));
        insert person;
        List<Rental__c> rentals = new List<Rental__c>();
        rentals.add(new Rental__c(Status__c = 'borrowed', Returning_Date__c = Date.today().addDays(-1), Borrower__c = person.Id, Item__c = book.Id));
        rentals.add(new Rental__c(Status__c = 'borrowed', Returning_Date__c = Date.today().addDays(-2), Borrower__c = person.Id, Item__c = book.Id));
        rentals.add(new Rental__c(Status__c = 'returned', Returning_Date__c = Date.today().addDays(-1), Borrower__c = person.Id, Item__c = book.Id));
        insert rentals;
    }

    @isTest
    static void testExecuteBatch() {
        Test.startTest();
        RentalStatusScheduler scheduler = new RentalStatusScheduler();
        String jobId = System.schedule('Test RentalStatusScheduler', '0 0 0 15 6 ? 2022', scheduler);
        Test.stopTest();

        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals('0 0 0 15 6 ? 2022', ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);

        Test.startTest();
        Database.executeBatch(scheduler);
        Test.stopTest();

        List<Rental__c> updatedRentals = [SELECT Id, Status__c, Returning_Date__c FROM Rental__c WHERE Status__c = 'delayed'];
        System.assertEquals(2, updatedRentals.size(), 'Two rentals should be delayed');
    }

    @isTest
    static void testBatchErrorHandling() {
        List<Rental__c> rentalsWithErrors = new List<Rental__c>();
        rentalsWithErrors.add(new Rental__c(Status__c = 'borrowed', Returning_Date__c = null,Borrower__c = null, Item__c = null));
        insert rentalsWithErrors;

        Test.startTest();
        RentalStatusScheduler scheduler = new RentalStatusScheduler();
        Database.executeBatch(scheduler);
        Test.stopTest();

        List<Rental__c> delayedRentals = [SELECT Id, Status__c FROM Rental__c WHERE Status__c = 'delayed'];
        System.assertEquals(2, delayedRentals.size(), 'Two rentals should be delayed from the previous test');

        List<Rental__c> errorRentals = [SELECT Id, Status__c FROM Rental__c WHERE Status__c = 'borrowed' AND Returning_Date__c = null];
        System.assertEquals(1, errorRentals.size(), 'One rental should remain borrowed due to error');
    }
}