force-app/main/default/objects/Item__c/fields/All_Copies__c.field-meta.xml
<CustomField>
    <fullName>All_Copies__c</fullName>
    <defaultValue>1</defaultValue>
    <label>All Copies</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/Item__c/recordTypes/Magazine.recordType-meta.xml
<RecordType>
    <fullName>Magazine</fullName>
    <active>true</active>
    <label>Magazine</label>
</RecordType>

force-app/main/default/classes/handler/ItemTriggerHandler.cls
public with sharing class ItemTriggerHandler {
    public static void onBeforeInsert(List<Item__c> newList) {
        for(Item__c item : newList) {
            if (item.RecordTypeId == RecordTypesUtility.getRecordTypeId(Item__c.SobjectType, 'Book')
            || item.RecordTypeId== RecordTypesUtility.getRecordTypeId(Item__c.SobjectType, 'Magazine')) {
                if (item.All_Copies__c < 1) {
                    item.addError('All copies cannot be less than 1 for Book or Magazine.');
                }
            }
        }
    }
}