force-app/main/default/objects/Item__c/fields/Available_Copies__c.field-meta.xml
<CustomField>
    <fullName>Available_Copies__c</fullName>
    <formula>All_Copies__c  -  Items_in_use__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Copies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Number_of_borrowed_items__c.field-meta.xml
<CustomField>
    <fullName>Number_of_borrowed_items__c</fullName>
    <label>Number of borrowed items</label>
    <summaryFilterItems>
        <field>Rental__c.Status__c</field>
        <operation>notEqual</operation>
        <value>turned</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Rental__c.Status__c</field>
        <operation>notEqual</operation>
        <value>reserved</value>
    </summaryFilterItems>
    <summaryForeignKey>Rental__c.Borrower__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Rental_Limitation__c.field-meta.xml
<CustomField>
    <fullName>Rental_Limitation__c</fullName>
    <defaultValue>(5)</defaultValue>
    <label>Rental Limitation</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Rent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/handler/TriggerHandler.cls
public without sharing class TriggerHandler {
	public static void checkIsBookAvailableForRental(List<Rental__c> newRentals) {
		Set<Id> itemIds = new Set<Id>();
		for (Rental__c rental : newRentals) {
			itemIds.add(rental.Item__c);
		}
		
		List<Item__c> items = [SELECT Id, Available_Copies__c FROM Item__c WHERE Id IN :itemIds];
		for(Item__c item : items) {
			if (item.Available_Copies__c < 1) {
				item.addError('Item is not available for rent');
			} else {
				item.Available_Copies__c -= 1;
			}
		}
		
		update items;
	}
	
	public static void checkNumberOfBorrowedItems(List<Rental__c> newRentals) {
		Set<Id> borrowerIds = new Set<Id>();
		Integer i=0;
		for (Rental__c rental : newRentals) {
			borrowerIds.add(rental.Borrower__c);
			i=i+1;
		}
		
		Map<Id, Person__c> borrowersMap = new Map<Id, Person__c>(
		[SELECT Id, Number_of_borrowed_items__c, Rental_Limitation__c
		FROM Person__c
		WHERE Id IN :borrowerIds]);
		
		for (Rental__c rental : newRentals) {
			Person__c borrower = borrowersMap.get(rental.Borrower__c);
			if (borrower.Number_of_borrowed_items__c >= borrower.Rental_Limitation__c) {
				rental.addError('Borrower has reached the rental limitation.');
			}
		}
	}
}