force-app/main/default/objects/Item__c/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/Item__c/recordTypes/Magazine.recordType-meta.xml
<RecordType>
    <fullName>Magazine</fullName>
    <active>true</active>
    <label>Magazine</label>
</RecordType>

force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Rent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Overdue_Payment__c.field-meta.xml
<CustomField>
    <fullName>Overdue_Payment__c</fullName>
    <formula>Weekdays_From_Due__c * CASE( Item__r.RecordType.Name, &quot;Book&quot;, $CustomMetadata.Overdue_Price__mdt.Book.Amount__c , &quot;Audiobook&quot;, $CustomMetadata.Overdue_Price__mdt.Audiobook.Amount__c , &quot;Magazine&quot;, $CustomMetadata.Overdue_Price__mdt.Magazine.Amount__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overdue Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>reserved</fullName>
                <default>true</default>
                <label>reserved</label>
            </value>
            <value>
                <fullName>borrowed</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/scheduled/AddOverdueFees.cls
public with sharing class AddOverdueFees implements Schedulable, Database.Stateful, Database.Batchable<SObject> {

    private Set<Id> errorToIDs = new Set<Id>();
    private Boolean isUpdateSuccessful = true;

    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new AddOverdueFees());
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        errorToIDs = new Set<Id>();
        isUpdateSuccessful = true;

        return Database.getQueryLocator([SELECT Id, Overdue_Payment__c,Item__c,Item__r.RecordTypeId  FROM Rental__c WHERE Status__c = 'delayed']);
    }

    public void execute(Database.BatchableContext context, List<Rental__c> rentals) {
        for (Rental__c rental : rentals) {
            if(rental.Item__r.RecordTypeId == RecordTypesUtility.getRecordTypeId(Item__c.SobjectType, 'Book')){
                rental.Overdue_Payment__c += 5;
            }
            if(rental.Item__r.RecordTypeId == RecordTypesUtility.getRecordTypeId(Item__c.SobjectType, 'Magazine')){
                rental.Overdue_Payment__c += 3;
            }
        }
        try {
            update rentals;
        } catch (Exception e) {
            isUpdateSuccessful = false;
            for (Rental__c rental : rentals) {
                errorToIDs.add(rental.Id);
            }
        }
    }

    public void finish(Database.BatchableContext context) {
        if (!isUpdateSuccessful) {
            System.debug('Error in RentalStatusScheduler Batch'+errorToIDs);
        }
    }
}