force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Rent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Returning_Date__c.field-meta.xml
<CustomField>
    <fullName>Returning_Date__c</fullName>
    <description>Date when an item should be returned to the library.</description>
    <label>Returning Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>reserved</fullName>
                <default>true</default>
                <label>reserved</label>
            </value>
            <value>
                <fullName>borrowed</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/scheduled/RentalStatusScheduler.cls
public class RentalStatusScheduler implements Schedulable, Database.Stateful, Database.Batchable<SObject>{
    

    private Set<Id> errorToIDs = new Set<Id>();

    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new RentalStatusScheduler());
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        errorToIDs = new Set<Id>();

        return Database.getQueryLocator([SELECT Id, Status__c, Returning_Date__c FROM Rental__c WHERE Returning_Date__c < TODAY AND Status__c = 'borrowed']);
    }

    public void execute(Database.BatchableContext context, List<Rental__c> rentals) {
        for (Rental__c rental : rentals) {
            rental.Status__c = 'delayed';
        }
        List<Database.SaveResult> results = Database.update(rentals, false);
            
        
        for (Integer i = 0; i < results.size(); i++) {
            if (!results[i].isSuccess()) {
                System.debug('Error in RentalStatusScheduler');
                System.debug(rentals[i].Id);
                System.debug(results[i].getErrors()[0].getMessage());
                errorToIDs.add(rentals[i].Id);
            }
        }
        
    }

    public void finish(Database.BatchableContext context) {
        if (errorToIDs.size() > 0) {
            System.debug('Error in RentalStatusScheduler Batch'+errorToIDs);
        }
    }

}