force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Pin__c.field-meta.xml
<CustomField>
    <fullName>Pin__c</fullName>
    <label>Pin</label>
    <length>6</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/PersonUtils.cls
public with sharing class PersonUtils {
    public static String generateNewPin() {
        String pin = '';

        for (Integer i = 0; i < 6; i++) {
            pin += String.valueOf(randomInteger()); 
        }

        return pin;
    }

    public static Integer randomInteger() {
        return Integer.valueOf(Math.floor(Math.random() * 10));
    }

    public static String getPin(Id personId) {
        Person__c person = [SELECT Id, Pin__c FROM Person__c WHERE Id = :personId];
        return person.Pin__c;
    }

    public static void setPin(Person__c person, String newPin) {
        if(newPin.length() != 6) {
            throw new System.StringException('The pin must be 6 characters long');
        }

        person.Pin__c = newPin;
        update person;
    }

    public static boolean isPinValid(String pin, Person__c person) {
        return pin == person.Pin__c;
    }
}